### ISSUE TITLE
Who can do what?

### ISSUE THREAD

**Issue by JackMcIlraith** [JackMcIlraith/SummerCampingTrip#1]
So, who wants to help?

We need somebody to do the following:
Location/destination
Food
Entertainment
Transportation

Feel free to chime in lads

**Comment by ghost** [comment]
I'll take transportation

**Comment by n1s** [comment]
I could do location

**Comment by Nayt-May** [comment]
ill take food....

**Comment by JackMcIlraith** [comment]
I'll take entertaiment
